/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Level {
  Error = 0,
  Warning = 1,
  Info = 2
}
export interface ValidationIssue {
  checkName: string
  level: string
  message: string
}
export interface ValidationReport {
  suiteName: string
  totalChecks: number
  passedChecks: number
  failedChecks: number
  issues: Array<ValidationIssue>
}
export interface PerformanceMetrics {
  totalDurationMs: number
  checksPerSecond: number
}
export interface ValidationResult {
  status: string
  report: ValidationReport
  metrics?: PerformanceMetrics
}
export const enum ConstraintStatus {
  Success = 0,
  Failure = 1,
  Skipped = 2
}
export declare function helloTerm(): string
export declare function getVersion(): string
export interface ValidationInfo {
  name: string
  version: string
  rustVersion: string
}
export declare function getInfo(): ValidationInfo
/** Example usage function demonstrating the full API */
export declare function validateSampleData(path: string): Promise<string>
export declare class Check {
  get name(): string
  get level(): Level
  get description(): string | null
}
export declare class CheckBuilder {
  constructor(name: string)
  level(level: Level): this
  description(desc: string): this
  isComplete(column: string, ratio?: number | undefined | null): Check
  hasMin(column: string, minValue: number): Check
  hasMax(column: string, maxValue: number): Check
  isUnique(column: string): Check
  hasMean(column: string, expected: number, tolerance?: number | undefined | null): Check
  build(): Check
}
export declare class DataSource {
  static fromParquet(path: string): Promise<DataSource>
  static fromCsv(path: string): Promise<DataSource>
  static fromJson(path: string): Promise<DataSource>
  getRowCount(): Promise<number>
  getColumnNames(): Promise<Array<string>>
  get tableName(): string
}
export declare class DataSourceBuilder {
  constructor()
  registerParquet(name: string, path: string): Promise<void>
  registerCsv(name: string, path: string): Promise<void>
  build(): DataSource
}
export declare class ValidationSuite {
  static builder(name: string): ValidationSuite
  get name(): string
  get description(): string | null
  run(data: DataSource): Promise<ValidationResult>
  get checkCount(): number
}
export declare class ValidationSuiteBuilder {
  constructor(name: string)
  description(desc: string): this
  addCheck(check: Check): this
  addChecks(checks: Array<Check>): this
  build(): ValidationSuite
}
