/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Level enum representing severity of validation checks
 */
export const enum Level {
  Error = 0,
  Warning = 1,
  Info = 2
}

/**
 * Status of a constraint evaluation
 */
export const enum ConstraintStatus {
  Success = 0,
  Failure = 1,
  Skipped = 2
}

/**
 * A validation issue found during suite execution
 */
export interface ValidationIssue {
  checkName: string
  level: string
  message: string
}

/**
 * Report containing validation results
 */
export interface ValidationReport {
  suiteName: string
  totalChecks: number
  passedChecks: number
  failedChecks: number
  issues: Array<ValidationIssue>
}

/**
 * Performance metrics for validation execution
 */
export interface PerformanceMetrics {
  totalDurationMs: number
  checksPerSecond: number
}

/**
 * Result of running a validation suite
 */
export interface ValidationResult {
  status: string
  report: ValidationReport
  metrics?: PerformanceMetrics
}

/**
 * Information about the Term Guard library
 */
export interface ValidationInfo {
  name: string
  version: string
  rustVersion: string
}

/**
 * A validation check that can be added to a validation suite
 */
export declare class Check {
  /** Get the name of this check */
  get name(): string
  /** Get the severity level of this check */
  get level(): Level
  /** Get the description of this check */
  get description(): string | null
}

/**
 * Builder for creating validation checks
 */
export declare class CheckBuilder {
  constructor(name: string)
  
  /** Set the severity level for this check */
  level(level: Level): this
  
  /** Set a description for this check */
  description(desc: string): this
  
  /** Create a completeness check for a column */
  isComplete(column: string, ratio?: number | undefined | null): Check
  
  /** Create a minimum value check for a column */
  hasMin(column: string, minValue: number): Check
  
  /** Create a maximum value check for a column */
  hasMax(column: string, maxValue: number): Check
  
  /** Create a uniqueness check for a column */
  isUnique(column: string): Check
  
  /** Create a mean value check for a column */
  hasMean(column: string, expected: number, tolerance?: number | undefined | null): Check
  
  /** Build a generic check */
  build(): Check
}

/**
 * A suite of validation checks to run against data
 */
export declare class ValidationSuite {
  /** Create a new ValidationSuiteBuilder */
  static builder(name: string): ValidationSuiteBuilder
  
  /** Get the name of this validation suite */
  get name(): string
  
  /** Get the description of this validation suite */
  get description(): string | null
  
  /** Get the number of checks in this suite */
  get checkCount(): number
  
  /** Run the validation suite against the provided data source */
  run(data: DataSource): Promise<ValidationResult>
}

/**
 * Builder for creating validation suites
 */
export declare class ValidationSuiteBuilder {
  constructor(name: string)
  
  /** Set a description for this validation suite */
  description(desc: string): this
  
  /** Add a single check to the validation suite */
  addCheck(check: Check): this
  
  /** Add multiple checks to the validation suite */
  addChecks(checks: Array<Check>): this
  
  /** Build the validation suite */
  build(): ValidationSuite
}

/**
 * A data source for validation
 */
export declare class DataSource {
  /** Create a DataSource from a Parquet file */
  static fromParquet(path: string): Promise<DataSource>
  
  /** Create a DataSource from a CSV file */
  static fromCsv(path: string): Promise<DataSource>
  
  /** Create a DataSource from a JSON file */
  static fromJson(path: string): Promise<DataSource>
  
  /** Get the row count of the data */
  getRowCount(): Promise<bigint>
  
  /** Get the column names of the data */
  getColumnNames(): Promise<Array<string>>
  
  /** Get the table name */
  get tableName(): string
}

/**
 * Builder for creating data sources with multiple tables
 */
export declare class DataSourceBuilder {
  constructor()
  
  /** Register a Parquet file as a table */
  registerParquet(name: string, path: string): Promise<this>
  
  /** Register a CSV file as a table */
  registerCsv(name: string, path: string): Promise<this>
  
  /** Build the DataSource */
  build(): DataSource
}

/** Get a greeting from Term Guard */
export function helloTerm(): string

/** Get the version of the Term Guard library */
export function getVersion(): string

/** Get information about the Term Guard library */
export function getInfo(): ValidationInfo

/** Example function to validate sample data */
export function validateSampleData(path: string): Promise<string>
