/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

const { platform, arch } = process;

let nativeBinding: any = null;
let localFileExisted = false;
let loadError: Error | null = null;

function isMusl(): boolean {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd 2>/dev/null', { encoding: 'utf8' });
      return readFileSync(lddPath, 'utf8').includes('musl');
    } catch (e) {
      return true;
    }
  } else {
    const { glibcVersionRuntime } = (process.report.getReport() as any).header;
    return !glibcVersionRuntime;
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'term-guard.android-arm64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.android-arm64.node');
          } else {
            nativeBinding = require('@withterm/term-guard-android-arm64');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'term-guard.android-arm-eabi.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.android-arm-eabi.node');
          } else {
            nativeBinding = require('@withterm/term-guard-android-arm-eabi');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`);
    }
    break;
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'term-guard.win32-x64-msvc.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.win32-x64-msvc.node');
          } else {
            nativeBinding = require('@withterm/term-guard-win32-x64-msvc');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'term-guard.win32-ia32-msvc.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.win32-ia32-msvc.node');
          } else {
            nativeBinding = require('@withterm/term-guard-win32-ia32-msvc');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'term-guard.win32-arm64-msvc.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.win32-arm64-msvc.node');
          } else {
            nativeBinding = require('@withterm/term-guard-win32-arm64-msvc');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'term-guard.darwin-universal.node'));
    try {
      if (localFileExisted) {
        nativeBinding = require('./term-guard.darwin-universal.node');
      } else {
        nativeBinding = require('@withterm/term-guard-darwin-universal');
      }
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'term-guard.darwin-x64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.darwin-x64.node');
          } else {
            nativeBinding = require('@withterm/term-guard-darwin-x64');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'term-guard.darwin-arm64.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.darwin-arm64.node');
          } else {
            nativeBinding = require('@withterm/term-guard-darwin-arm64');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`);
    }
    localFileExisted = existsSync(join(__dirname, 'term-guard.freebsd-x64.node'));
    try {
      if (localFileExisted) {
        nativeBinding = require('./term-guard.freebsd-x64.node');
      } else {
        nativeBinding = require('@withterm/term-guard-freebsd-x64');
      }
    } catch (e) {
      loadError = e as Error;
    }
    break;
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'term-guard.linux-x64-musl.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./term-guard.linux-x64-musl.node');
            } else {
              nativeBinding = require('@withterm/term-guard-linux-x64-musl');
            }
          } catch (e) {
            loadError = e as Error;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'term-guard.linux-x64-gnu.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./term-guard.linux-x64-gnu.node');
            } else {
              nativeBinding = require('@withterm/term-guard-linux-x64-gnu');
            }
          } catch (e) {
            loadError = e as Error;
          }
        }
        break;
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'term-guard.linux-arm64-musl.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./term-guard.linux-arm64-musl.node');
            } else {
              nativeBinding = require('@withterm/term-guard-linux-arm64-musl');
            }
          } catch (e) {
            loadError = e as Error;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'term-guard.linux-arm64-gnu.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./term-guard.linux-arm64-gnu.node');
            } else {
              nativeBinding = require('@withterm/term-guard-linux-arm64-gnu');
            }
          } catch (e) {
            loadError = e as Error;
          }
        }
        break;
      case 'arm':
        localFileExisted = existsSync(
          join(__dirname, 'term-guard.linux-arm-gnueabihf.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./term-guard.linux-arm-gnueabihf.node');
          } else {
            nativeBinding = require('@withterm/term-guard-linux-arm-gnueabihf');
          }
        } catch (e) {
          loadError = e as Error;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(`Failed to load native binding`);
}

export = nativeBinding;