/* auto-generated by NAPI-RS */

export interface TermGuardInfo {
  name: string;
  version: string;
  rustVersion: string;
}

/**
 * Returns a greeting from Term Guard
 */
export function helloTerm(): string;

/**
 * Returns the current version of Term Guard
 */
export function getVersion(): string;

/**
 * Returns information about the Term Guard library
 */
export function getInfo(): TermGuardInfo;

/**
 * Validates sample data asynchronously
 */
export function validateSampleData(): Promise<string>;